### ISSUE TITLE
Cannot setup - fatal error

### ISSUE THREAD

**Issue by kennedybaird** [monero-integrations/monerowp#64]
Hi there

I get this error when putting the monero address into and clicking go (note, have to turn WP_DEBUG to true):

```
Fatal error: Uncaught Error: Call to undefined function bcdiv() in /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/base58.php:313
Stack trace: #0 /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/cryptonote.php(233): base58->decode(Array)
#1 /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/monero_payments.php(277): Cryptonote->verify_checksum('46amisAS55Nei3p...')
#2 /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/monero_payments.php(255): Monero_Gateway->check_monero()
#3 /var/www/html/wp-includes/class-wp-hook.php(286): Monero_Gateway->validate_fields('')
#4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/html/wp-admin/admin-header.php(255): do_action('admin_notices')
#7 /var/www/html/wp-admin/admin.php(216): require_once('/var/www/html/w...')
#8 {main} thrown in /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/base58.php on line 313
```

These are the settings in MySQL (i have buffered out the address):
```
a:13:{s:7:"enabled";s:3:"yes";s:5:"title";s:18:"Monero XMR Payment";s:11:"description";s:23:"Pay securely using XMR.";s:11:"use_viewKey";s:2:"no";s:14:"monero_address";s:95:"[--* address *--]";s:7:"viewKey";s:0:"";s:7:"use_rpc";s:2:"no";s:11:"daemon_host";s:23:"oc.node.moneroworld.com";s:11:"daemon_port";s:5:"18089";s:8:"discount";s:1:"5";s:11:"environment";s:2:"no";s:9:"zero_conf";s:2:"no";s:13:"onion_service";s:2:"no";}
```

Note, this only happens when I put the address in. And it then bricks everything because of the error and then have to edit via MySQL to recover access to WooCommerce / monero settings.

It happens with enabled set to `yes` or `no` and with default `daemon_host`

**Comment by kennedybaird** [comment]
Sigh, installed `bcmath`..

https://askubuntu.com/questions/416866/how-can-i-get-the-bcmath-plugin-in-php5-in-ubuntu
